---
defaultStorageEngineId: "${OPENCGA.STORAGE.ENGINE.DEFAULT}"
logLevel: "info"
logFile: ""

## This value can be set up using maven profiles in your .m2/settings.xml
studyMetadataManager: "${OPENCGA.STORAGE.STUDY.METADATA.MANAGER}"

## CellBase client configuration, this is used mainly when annotating variants
## This can be set up using maven profiles in your .m2/settings.xml
cellbase:
  hosts:      ## 'remote' URL hosts to annotate variants, for example: http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/
  - "${OPENCGA.CELLBASE.HOST}"
  version: "${OPENCGA.CELLBASE.VERSION}"
  database:   ## 'local' connection to CellBase MongoDB
    hosts:
    - ""
    user: ""
    password: ""
    options: {}         ## This is intended for database specific options such as --authenticationDatabase in MongoDB
  preferred: "remote"   ## This accept two values: 'local' and 'remote' to fetch data

## Storage Query Server configuration. When CLI is launched in 'server' mode a RESTful web server
## is launched in the specified port. Only authorized hosts are allowed to query data.
server:
  rest: 9090
  grpc: 9091
  authManager: "org.opencb.opencga.storage.server.common.DefaultAuthManager"       ## Path to the AuthManager implementation class
  storageEngine: "mongodb"
  authorizedHosts: ["0.0.0.0"]
  options: {}

benchmark:
  storageEngine: "mongodb"
  numRepetitions: 3
  load: false
  queries: ["count", "distinct"]
  databaseName: "opencga"
  table: "variants"
  concurrency: 1
  database:   ## 'local' connection to CellBase MongoDB
      hosts:
      - "localhost:27017"
      user: ""
      password: ""
      options: {}         ## This is intended for database specific options such as --authenticationDatabase in MongoDB

## The following section defines all availables storage engine plugins installed
## Default plugin is 'mongodb' storage engine
storageEngines:
- id: "mongodb"
  options: {}     ## this field is intended to be removed, try not to use it.
  alignment:
    manager: "org.opencb.opencga.storage.mongodb.alignment.MongoDBAlignmentStorageManager"
    options:
      database.name: "opencga"
      tools.samtools: "${OPENCGA.INSTALLATION.DIR}/tools/samtools/samtools"
      transform.region_size: 200000
      transform.coverage_chunk_size: 1000
      mean_coverage_size_list: [200, 10000]
    database:
      hosts:
      - "${OPENCGA.STORAGE.ALIGNMENT.DB.HOSTS}"
      user: "${OPENCGA.STORAGE.ALIGNMENT.DB.USER}"
      password: "${OPENCGA.STORAGE.ALIGNMENT.DB.PASSWORD}"
      options: {}
  variant:
    manager: "org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageManager"
    options:
      database.name: "opencga"
      collection.variants: "variants"
      collection.studies: "studies"
      collection.files: "files"
      include.stats: false
      annotator: cellbase_rest
      species: "hsapiens"
      assembly: "GRCh37"
      transform.batch.size: 200
      transform.threads: 4
      transform.format: "avro"
      load.batch.size: 100
      load.threads: 6
      #load.bulk_size: 100
      #load.compress_genotypes: true
    database:
      hosts:
      - "${OPENCGA.STORAGE.VARIANT.DB.HOSTS}"
      user: "${OPENCGA.STORAGE.VARIANT.DB.USER}"
      password: "${OPENCGA.STORAGE.VARIANT.DB.PASSWORD}"
      options:    ## This is intended for database specific options such as --authenticationDatabase in MongoDB
        authenticationDatabase: ${OPENCGA.STORAGE.VARIANT.DB.AUTHENTICATION_DATABASE}
        readPreference: "secondaryPreferred"

## For using this plugin you need to have a Hadoop cluster and run the CLI from a well configured Hadoop client
- id: "hadoop"
  options: {}
  alignment:
    manager: "org.opencb.opencga.storage.hadoop.alignment.MongoDBAlignmentStorageManager"
    options: {}
    database:
      hosts:
      - "${OPENCGA.STORAGE.VARIANT.DB.HOSTS}"
      user: "${OPENCGA.STORAGE.VARIANT.DB.USER}"
      password: "${OPENCGA.STORAGE.VARIANT.DB.PASSWORD}"
  variant:
    manager: "org.opencb.opencga.storage.hadoop.variant.HadoopVariantStorageManager"
    options:
      #Generic options
      database.name: "opencga"
      annotator: cellbase_rest
      species: "hsapiens"
      assembly: "GRCh37"
      #Plugin specific options
      hadoop.bin: "hadoop"
#      hadoop.env: # See opencga-env.sh
#      - "HADOOP_USER_CLASSPATH_FIRST=true"
#      - "HADOOP_CLASSPATH=$HADOOP_CLASSPATH:${OPENCGA.INSTALLATION.DIR}/libs/protobuf-java-${google.protobuf}.jar"
#      - ....
      opencga.storage.hadoop.jar-with-dependencies: "opencga-storage-hadoop-${opencga.version}-jar-with-dependencies.jar"
      opencga.archive.chunk_size: 1000
      opencga.archive.table.compression: "snappy"
      opencga.variant.table.compression: "snappy"
      opencga.storage.hadoop.hbase.namespace: "${OPENCGA.STORAGE.HADOOP.HBASE.NAMESPACE}"
      opencga.storage.hadoop.hbase.archive.table.prefix: "${OPENCGA.STORAGE.HADOOP.HBASE.ARCHIVE.TABLE.PREFIX}"
      # Increase the ScannerTimeoutPeriod from 60000 (1min) to 300000 (5min) to avoid ScannerTimeoutExceptions
      # See opencb/opencga#352 for more info.
      opencga.storage.hadoop.mapreduce.scanner.timeout: 300000
      #Hadoop options
      #fs.defaultFS: "${OPENCGA.STORAGE.HADOOP.HDFS.DEFAULT_FS}"
    database:
      hosts:
      - "${OPENCGA.STORAGE.HADOOP.VARIANT.DB.HOSTS}"
      user: "${OPENCGA.STORAGE.HADOOP.VARIANT.DB.USER}"
      password: "${OPENCGA.STORAGE.HADOOP.VARIANT.DB.PASSWORD}"
