# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GenericService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GenericService.proto',
  package='org.opencb.opencga.storage.server.grpc',
  syntax='proto3',
  serialized_pb=_b('\n\x14GenericService.proto\x12&org.opencb.opencga.storage.server.grpc\"\xd6\x02\n\x07Request\x12\x15\n\rstorageEngine\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61tabase\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\n\n\x02ip\x18\x05 \x01(\t\x12I\n\x05query\x18\x06 \x03(\x0b\x32:.org.opencb.opencga.storage.server.grpc.Request.QueryEntry\x12M\n\x07options\x18\x07 \x03(\x0b\x32<.org.opencb.opencga.storage.server.grpc.Request.OptionsEntry\x1a,\n\nQueryEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0cOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1d\n\x0cLongResponse\x12\r\n\x05value\x18\x01 \x01(\x03\"\x1f\n\x0eStringResponse\x12\r\n\x05value\x18\x01 \x01(\t\"%\n\x13StringArrayResponse\x12\x0e\n\x06values\x18\x01 \x03(\t\"\x91\x01\n\rGroupResponse\x12Q\n\x06values\x18\x01 \x03(\x0b\x32\x41.org.opencb.opencga.storage.server.grpc.GroupResponse.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8d\x01\n\x0bMapResponse\x12O\n\x06values\x18\x01 \x03(\x0b\x32?.org.opencb.opencga.storage.server.grpc.MapResponse.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x15\x42\x13GenericServiceModelb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQUEST_QUERYENTRY = _descriptor.Descriptor(
  name='QueryEntry',
  full_name='org.opencb.opencga.storage.server.grpc.Request.QueryEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='org.opencb.opencga.storage.server.grpc.Request.QueryEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='org.opencb.opencga.storage.server.grpc.Request.QueryEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=359,
)

_REQUEST_OPTIONSENTRY = _descriptor.Descriptor(
  name='OptionsEntry',
  full_name='org.opencb.opencga.storage.server.grpc.Request.OptionsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='org.opencb.opencga.storage.server.grpc.Request.OptionsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='org.opencb.opencga.storage.server.grpc.Request.OptionsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=407,
)

_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='org.opencb.opencga.storage.server.grpc.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='storageEngine', full_name='org.opencb.opencga.storage.server.grpc.Request.storageEngine', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='database', full_name='org.opencb.opencga.storage.server.grpc.Request.database', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user', full_name='org.opencb.opencga.storage.server.grpc.Request.user', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='org.opencb.opencga.storage.server.grpc.Request.password', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='org.opencb.opencga.storage.server.grpc.Request.ip', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='query', full_name='org.opencb.opencga.storage.server.grpc.Request.query', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='options', full_name='org.opencb.opencga.storage.server.grpc.Request.options', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_QUERYENTRY, _REQUEST_OPTIONSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=407,
)


_LONGRESPONSE = _descriptor.Descriptor(
  name='LongResponse',
  full_name='org.opencb.opencga.storage.server.grpc.LongResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='org.opencb.opencga.storage.server.grpc.LongResponse.value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=438,
)


_STRINGRESPONSE = _descriptor.Descriptor(
  name='StringResponse',
  full_name='org.opencb.opencga.storage.server.grpc.StringResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='org.opencb.opencga.storage.server.grpc.StringResponse.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=471,
)


_STRINGARRAYRESPONSE = _descriptor.Descriptor(
  name='StringArrayResponse',
  full_name='org.opencb.opencga.storage.server.grpc.StringArrayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='org.opencb.opencga.storage.server.grpc.StringArrayResponse.values', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=473,
  serialized_end=510,
)


_GROUPRESPONSE_VALUESENTRY = _descriptor.Descriptor(
  name='ValuesEntry',
  full_name='org.opencb.opencga.storage.server.grpc.GroupResponse.ValuesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='org.opencb.opencga.storage.server.grpc.GroupResponse.ValuesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='org.opencb.opencga.storage.server.grpc.GroupResponse.ValuesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=613,
  serialized_end=658,
)

_GROUPRESPONSE = _descriptor.Descriptor(
  name='GroupResponse',
  full_name='org.opencb.opencga.storage.server.grpc.GroupResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='org.opencb.opencga.storage.server.grpc.GroupResponse.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GROUPRESPONSE_VALUESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=513,
  serialized_end=658,
)


_MAPRESPONSE_VALUESENTRY = _descriptor.Descriptor(
  name='ValuesEntry',
  full_name='org.opencb.opencga.storage.server.grpc.MapResponse.ValuesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='org.opencb.opencga.storage.server.grpc.MapResponse.ValuesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='org.opencb.opencga.storage.server.grpc.MapResponse.ValuesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=613,
  serialized_end=658,
)

_MAPRESPONSE = _descriptor.Descriptor(
  name='MapResponse',
  full_name='org.opencb.opencga.storage.server.grpc.MapResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='org.opencb.opencga.storage.server.grpc.MapResponse.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MAPRESPONSE_VALUESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=661,
  serialized_end=802,
)

_REQUEST_QUERYENTRY.containing_type = _REQUEST
_REQUEST_OPTIONSENTRY.containing_type = _REQUEST
_REQUEST.fields_by_name['query'].message_type = _REQUEST_QUERYENTRY
_REQUEST.fields_by_name['options'].message_type = _REQUEST_OPTIONSENTRY
_GROUPRESPONSE_VALUESENTRY.containing_type = _GROUPRESPONSE
_GROUPRESPONSE.fields_by_name['values'].message_type = _GROUPRESPONSE_VALUESENTRY
_MAPRESPONSE_VALUESENTRY.containing_type = _MAPRESPONSE
_MAPRESPONSE.fields_by_name['values'].message_type = _MAPRESPONSE_VALUESENTRY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['LongResponse'] = _LONGRESPONSE
DESCRIPTOR.message_types_by_name['StringResponse'] = _STRINGRESPONSE
DESCRIPTOR.message_types_by_name['StringArrayResponse'] = _STRINGARRAYRESPONSE
DESCRIPTOR.message_types_by_name['GroupResponse'] = _GROUPRESPONSE
DESCRIPTOR.message_types_by_name['MapResponse'] = _MAPRESPONSE

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(

  QueryEntry = _reflection.GeneratedProtocolMessageType('QueryEntry', (_message.Message,), dict(
    DESCRIPTOR = _REQUEST_QUERYENTRY,
    __module__ = 'GenericService_pb2'
    # @@protoc_insertion_point(class_scope:org.opencb.opencga.storage.server.grpc.Request.QueryEntry)
    ))
  ,

  OptionsEntry = _reflection.GeneratedProtocolMessageType('OptionsEntry', (_message.Message,), dict(
    DESCRIPTOR = _REQUEST_OPTIONSENTRY,
    __module__ = 'GenericService_pb2'
    # @@protoc_insertion_point(class_scope:org.opencb.opencga.storage.server.grpc.Request.OptionsEntry)
    ))
  ,
  DESCRIPTOR = _REQUEST,
  __module__ = 'GenericService_pb2'
  # @@protoc_insertion_point(class_scope:org.opencb.opencga.storage.server.grpc.Request)
  ))
_sym_db.RegisterMessage(Request)
_sym_db.RegisterMessage(Request.QueryEntry)
_sym_db.RegisterMessage(Request.OptionsEntry)

LongResponse = _reflection.GeneratedProtocolMessageType('LongResponse', (_message.Message,), dict(
  DESCRIPTOR = _LONGRESPONSE,
  __module__ = 'GenericService_pb2'
  # @@protoc_insertion_point(class_scope:org.opencb.opencga.storage.server.grpc.LongResponse)
  ))
_sym_db.RegisterMessage(LongResponse)

StringResponse = _reflection.GeneratedProtocolMessageType('StringResponse', (_message.Message,), dict(
  DESCRIPTOR = _STRINGRESPONSE,
  __module__ = 'GenericService_pb2'
  # @@protoc_insertion_point(class_scope:org.opencb.opencga.storage.server.grpc.StringResponse)
  ))
_sym_db.RegisterMessage(StringResponse)

StringArrayResponse = _reflection.GeneratedProtocolMessageType('StringArrayResponse', (_message.Message,), dict(
  DESCRIPTOR = _STRINGARRAYRESPONSE,
  __module__ = 'GenericService_pb2'
  # @@protoc_insertion_point(class_scope:org.opencb.opencga.storage.server.grpc.StringArrayResponse)
  ))
_sym_db.RegisterMessage(StringArrayResponse)

GroupResponse = _reflection.GeneratedProtocolMessageType('GroupResponse', (_message.Message,), dict(

  ValuesEntry = _reflection.GeneratedProtocolMessageType('ValuesEntry', (_message.Message,), dict(
    DESCRIPTOR = _GROUPRESPONSE_VALUESENTRY,
    __module__ = 'GenericService_pb2'
    # @@protoc_insertion_point(class_scope:org.opencb.opencga.storage.server.grpc.GroupResponse.ValuesEntry)
    ))
  ,
  DESCRIPTOR = _GROUPRESPONSE,
  __module__ = 'GenericService_pb2'
  # @@protoc_insertion_point(class_scope:org.opencb.opencga.storage.server.grpc.GroupResponse)
  ))
_sym_db.RegisterMessage(GroupResponse)
_sym_db.RegisterMessage(GroupResponse.ValuesEntry)

MapResponse = _reflection.GeneratedProtocolMessageType('MapResponse', (_message.Message,), dict(

  ValuesEntry = _reflection.GeneratedProtocolMessageType('ValuesEntry', (_message.Message,), dict(
    DESCRIPTOR = _MAPRESPONSE_VALUESENTRY,
    __module__ = 'GenericService_pb2'
    # @@protoc_insertion_point(class_scope:org.opencb.opencga.storage.server.grpc.MapResponse.ValuesEntry)
    ))
  ,
  DESCRIPTOR = _MAPRESPONSE,
  __module__ = 'GenericService_pb2'
  # @@protoc_insertion_point(class_scope:org.opencb.opencga.storage.server.grpc.MapResponse)
  ))
_sym_db.RegisterMessage(MapResponse)
_sym_db.RegisterMessage(MapResponse.ValuesEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\023GenericServiceModel'))
_REQUEST_QUERYENTRY.has_options = True
_REQUEST_QUERYENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_REQUEST_OPTIONSENTRY.has_options = True
_REQUEST_OPTIONSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_GROUPRESPONSE_VALUESENTRY.has_options = True
_GROUPRESPONSE_VALUESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_MAPRESPONSE_VALUESENTRY.has_options = True
_MAPRESPONSE_VALUESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
import abc
import six
from grpc.beta import implementations as beta_implementations
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
